name: Push Verify

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Push Verify
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: brynnaleslie/reusableworkflows/.github/workflows/reusable-build.yml@main

        with:
          dotnet-version: 9.0.x
